// file: DoblePuntaOntology.java generated by ontology bean generator.  DO NOT EDIT, UNLESS YOU ARE REALLY SURE WHAT YOU ARE DOING!
package ontologias;

import jade.content.onto.*;
import jade.content.schema.*;

/** file: DoblePuntaOntology.java
 * @author ontology bean generator
 * @version 2009/10/6, 20:18:13
 */
public class DoblePuntaOntology extends jade.content.onto.Ontology  {
  //NAME
  public static final String ONTOLOGY_NAME = "DoblePunta";
  // The singleton instance of this ontology
  private static ReflectiveIntrospector introspect = new ReflectiveIntrospector();
  private static Ontology theInstance = new DoblePuntaOntology();
  public static Ontology getInstance() {
     return theInstance;
  }


   // VOCABULARY
    public static final String PREDICADOFINREGISTRO_FINREGISTRO="finRegistro";
    public static final String PREDICADOFINREGISTRO="PredicadoFinRegistro";
    public static final String PREDICADOINICIOSUBASTA_INICIOSUBASTA="inicioSubasta";
    public static final String PREDICADOINICIOSUBASTA="PredicadoInicioSubasta";
    public static final String PREDICADOREGISTRARVENTA_OFERTAVENTA="ofertaVenta";
    public static final String PREDICADOREGISTRARVENTA_PRODUCTO="producto";
    public static final String PREDICADOREGISTRARVENTA="PredicadoRegistrarVenta";
    public static final String PREDICADOENESPERA_ENESPERA="enEspera";
    public static final String PREDICADOENESPERA="PredicadoEnEspera";
    public static final String PREDICADOREGISTRARCOMPRA_PRODUCTO="producto";
    public static final String PREDICADOREGISTRARCOMPRA_OFERTACOMPRA="ofertaCompra";
    public static final String PREDICADOREGISTRARCOMPRA="PredicadoRegistrarCompra";
    public static final String PREDICADOCANCELARVENTA_OFERTAVENTA="ofertaVenta";
    public static final String PREDICADOCANCELARVENTA="PredicadoCancelarVenta";
    public static final String PREDICADOCONFIRMAROFERTA_CONFIRMACIONOFERTA="confirmacionOferta";
    public static final String PREDICADOCONFIRMAROFERTA="PredicadoConfirmarOferta";
    public static final String PREDICADONOTIFICARVENTA_NOTIFICACIONVENTA="notificacionVenta";
    public static final String PREDICADONOTIFICARVENTA="PredicadoNotificarVenta";
    public static final String PREDICADOMODIFICARCOMPRA_OFERTACOMPRA="ofertaCompra";
    public static final String PREDICADOMODIFICARCOMPRA="PredicadoModificarCompra";
    public static final String PREDICADOMODIFICARVENTA_OFERTAVENTA="ofertaVenta";
    public static final String PREDICADOMODIFICARVENTA="PredicadoModificarVenta";
    public static final String PREDICADOCONFIRMARREGISTRO_REGISTRO="registro";
    public static final String PREDICADOCONFIRMARREGISTRO="PredicadoConfirmarRegistro";
    public static final String PREDICADONOTIFICARCOMPRA_NOTIFICACIONCOMPRA="notificacionCompra";
    public static final String PREDICADONOTIFICARCOMPRA="PredicadoNotificarCompra";
    public static final String PREDICADOFINSUBASTA_FINSUBASTA="finSubasta";
    public static final String PREDICADOFINSUBASTA="PredicadoFinSubasta";
    public static final String PREDICADOCANCELARCOMPRA_OFERTACOMPRA="ofertaCompra";
    public static final String PREDICADOCANCELARCOMPRA="PredicadoCancelarCompra";
    public static final String PREDICADOREGISTRARAGENTEBURSATIL_BURSATIL="bursatil";
    public static final String PREDICADOREGISTRARAGENTEBURSATIL="PredicadoRegistrarAgenteBursatil";

 
    public static final String CONCEPTOOFERTAVENTA_PERIODO="periodo";
    
    public static final String CONCEPTOOFERTAVENTA_CANTIDAD="cantidad";
    public static final String CONCEPTOOFERTAVENTA_IDOFERTAVENTA="IDOfertaVenta";
    public static final String CONCEPTOOFERTAVENTA_IDVENDEDOR="IDVendedor";
    public static final String CONCEPTOOFERTAVENTA_PRECIOVENTA="precioVenta";
    public static final String CONCEPTOOFERTAVENTA_FECHA="fecha";
    public static final String CONCEPTOOFERTAVENTA="ConceptoOfertaVenta";
    public static final String CONCEPTOREGISTRO_IDBURSATIL="IDBursatil";
    public static final String CONCEPTOREGISTRO_FECHA="fecha";
    public static final String CONCEPTOREGISTRO="ConceptoRegistro";
    public static final String CONCEPTOCALCE_CANTIDAD="cantidad";
    public static final String CONCEPTOCALCE_IDOFERTAVENTA="IDOfertaVenta";
    public static final String CONCEPTOCALCE_PRECIOSUGERIDO="precioSugerido";
    public static final String CONCEPTOCALCE_IDPRODUCTO="IDProducto";
    public static final String CONCEPTOCALCE_IDCALCE="IDCalce";
    public static final String CONCEPTOCALCE_FECHA="fecha";
    public static final String CONCEPTOCALCE_IDOFERTACOMPRA="IDOfertaCompra";
    public static final String CONCEPTOCALCE="ConceptoCalce";


    public static final String CONCEPTOOFERTACOMPRA_PERIODO="periodo";

    public static final String CONCEPTOOFERTACOMPRA_CANTIDAD="cantidad";
    public static final String CONCEPTOOFERTACOMPRA_PRECIOCOMPRA="precioCompra";
    public static final String CONCEPTOOFERTACOMPRA_IDCOMPRADOR="IDComprador";
    public static final String CONCEPTOOFERTACOMPRA_FECHA="fecha";
    public static final String CONCEPTOOFERTACOMPRA_IDOFERTACOMPRA="IDOfertaCompra";
    public static final String CONCEPTOOFERTACOMPRA="ConceptoOfertaCompra";
    public static final String CONCEPTONOTIFICACIONCOMPRA_CANTIDAD="cantidad";
    public static final String CONCEPTONOTIFICACIONCOMPRA_IDPRODUCTO="IDProducto";
    public static final String CONCEPTONOTIFICACIONCOMPRA_IDNOTIFICACIONCOMPRA="IDNotificacionCompra";
    public static final String CONCEPTONOTIFICACIONCOMPRA_IDCOMPRADOR="IDComprador";
    public static final String CONCEPTONOTIFICACIONCOMPRA_FECHA="fecha";
    public static final String CONCEPTONOTIFICACIONCOMPRA_PRECIO="precio";
    public static final String CONCEPTONOTIFICACIONCOMPRA="ConceptoNotificacionCompra";
    public static final String CONCEPTOBURSATIL_IDBURSATIL="IDBursatil";
    public static final String CONCEPTOBURSATIL_TIPO="tipo";
    public static final String CONCEPTOBURSATIL_NOMBRE="nombre";
    public static final String CONCEPTOBURSATIL_SALDO="saldo";
    public static final String CONCEPTOBURSATIL="ConceptoBursatil";
    public static final String CONCEPTONOTIFICACIONVENTA_CANTIDAD="cantidad";
    public static final String CONCEPTONOTIFICACIONVENTA_IDVENDEDOR="IDVendedor";
    public static final String CONCEPTONOTIFICACIONVENTA_IDPRODUCTO="IDProducto";
    public static final String CONCEPTONOTIFICACIONVENTA_IDNOTIFICACIONVENTA="IDNotificacionVenta";
    public static final String CONCEPTONOTIFICACIONVENTA_FECHA="fecha";
    public static final String CONCEPTONOTIFICACIONVENTA_PRECIO="precio";
    public static final String CONCEPTONOTIFICACIONVENTA="ConceptoNotificacionVenta";
    public static final String CONCEPTOPRODUCTO_IDPRODUCTO="IDProducto";
    public static final String CONCEPTOPRODUCTO_NOMBRE="nombre";
    public static final String CONCEPTOPRODUCTO_DESCRIPCION="descripcion";
    public static final String CONCEPTOPRODUCTO="ConceptoProducto";

    public static final String PREDICADOINICIOCALLMARKET="PredicadoInicionCallMarket";
    public static final String PREDICADOINICIOCALLMARKET_PRODUCTO="producto";
    public static final String PREDICADOINICIOCALLMARKET_MOMENTO="momento";

    public static final String PREDICADOFINCALLMARKET="PredicadoFinCallMarket";
    public static final String PREDICADOFINCALLMARKET_PRODUCTO="producto";
    public static final String PREDICADOFINCALLMARKET_MOMENTO="momento";

    public static final String PREDICADOCANCELARVENTA_CONCEPTO="concepto";
    public static final String PREDICADOCANCELARCOMPRA_CONCEPTO="concepto";

    public static final String PREDICADOCANCELARVENTA_PRODUCTO="IDProducto";
    public static final String PREDICADOCANCELARCOMPRA_PRODUCTO="IDProducto";
    

  /**
   * Constructor
  */
  private DoblePuntaOntology(){ 
    super(ONTOLOGY_NAME, BasicOntology.getInstance());
    try { 

    // adding Concept(s)
    ConceptSchema conceptoProductoSchema = new ConceptSchema(CONCEPTOPRODUCTO);
    add(conceptoProductoSchema, ontologias.ConceptoProducto.class);
    ConceptSchema conceptoNotificacionVentaSchema = new ConceptSchema(CONCEPTONOTIFICACIONVENTA);
    add(conceptoNotificacionVentaSchema, ontologias.ConceptoNotificacionVenta.class);
    ConceptSchema conceptoBursatilSchema = new ConceptSchema(CONCEPTOBURSATIL);
    add(conceptoBursatilSchema, ontologias.ConceptoBursatil.class);
    ConceptSchema conceptoNotificacionCompraSchema = new ConceptSchema(CONCEPTONOTIFICACIONCOMPRA);
    add(conceptoNotificacionCompraSchema, ontologias.ConceptoNotificacionCompra.class);
    ConceptSchema conceptoOfertaCompraSchema = new ConceptSchema(CONCEPTOOFERTACOMPRA);
    add(conceptoOfertaCompraSchema, ontologias.ConceptoOfertaCompra.class);
    ConceptSchema conceptoCalceSchema = new ConceptSchema(CONCEPTOCALCE);
    add(conceptoCalceSchema, ontologias.ConceptoCalce.class);
    ConceptSchema conceptoRegistroSchema = new ConceptSchema(CONCEPTOREGISTRO);
    add(conceptoRegistroSchema, ontologias.ConceptoRegistro.class);
    ConceptSchema conceptoOfertaVentaSchema = new ConceptSchema(CONCEPTOOFERTAVENTA);
    add(conceptoOfertaVentaSchema, ontologias.ConceptoOfertaVenta.class);

    // adding AgentAction(s)

    // adding AID(s)

    // adding Predicate(s)
    PredicateSchema predicadoRegistrarAgenteBursatilSchema = new PredicateSchema(PREDICADOREGISTRARAGENTEBURSATIL);
    add(predicadoRegistrarAgenteBursatilSchema, ontologias.PredicadoRegistrarAgenteBursatil.class);
    PredicateSchema predicadoCancelarCompraSchema = new PredicateSchema(PREDICADOCANCELARCOMPRA);
    add(predicadoCancelarCompraSchema, ontologias.PredicadoCancelarCompra.class);
    PredicateSchema predicadoFinSubastaSchema = new PredicateSchema(PREDICADOFINSUBASTA);
    add(predicadoFinSubastaSchema, ontologias.PredicadoFinSubasta.class);
    PredicateSchema predicadoNotificarCompraSchema = new PredicateSchema(PREDICADONOTIFICARCOMPRA);
    add(predicadoNotificarCompraSchema, ontologias.PredicadoNotificarCompra.class);
    PredicateSchema predicadoConfirmarRegistroSchema = new PredicateSchema(PREDICADOCONFIRMARREGISTRO);
    add(predicadoConfirmarRegistroSchema, ontologias.PredicadoConfirmarRegistro.class);
    PredicateSchema predicadoModificarVentaSchema = new PredicateSchema(PREDICADOMODIFICARVENTA);
    add(predicadoModificarVentaSchema, ontologias.PredicadoModificarVenta.class);
    PredicateSchema predicadoModificarCompraSchema = new PredicateSchema(PREDICADOMODIFICARCOMPRA);
    add(predicadoModificarCompraSchema, ontologias.PredicadoModificarCompra.class);
    PredicateSchema predicadoNotificarVentaSchema = new PredicateSchema(PREDICADONOTIFICARVENTA);
    add(predicadoNotificarVentaSchema, ontologias.PredicadoNotificarVenta.class);
    PredicateSchema predicadoConfirmarOfertaSchema = new PredicateSchema(PREDICADOCONFIRMAROFERTA);
    add(predicadoConfirmarOfertaSchema, ontologias.PredicadoConfirmarOferta.class);
    PredicateSchema predicadoCancelarVentaSchema = new PredicateSchema(PREDICADOCANCELARVENTA);
    add(predicadoCancelarVentaSchema, ontologias.PredicadoCancelarVenta.class);
    PredicateSchema predicadoRegistrarCompraSchema = new PredicateSchema(PREDICADOREGISTRARCOMPRA);
    add(predicadoRegistrarCompraSchema, ontologias.PredicadoRegistrarCompra.class);
    PredicateSchema predicadoEnEsperaSchema = new PredicateSchema(PREDICADOENESPERA);
    add(predicadoEnEsperaSchema, ontologias.PredicadoEnEspera.class);
    PredicateSchema predicadoRegistrarVentaSchema = new PredicateSchema(PREDICADOREGISTRARVENTA);
    add(predicadoRegistrarVentaSchema, ontologias.PredicadoRegistrarVenta.class);
    PredicateSchema predicadoInicioSubastaSchema = new PredicateSchema(PREDICADOINICIOSUBASTA);
    add(predicadoInicioSubastaSchema, ontologias.PredicadoInicioSubasta.class);
    PredicateSchema predicadoFinRegistroSchema = new PredicateSchema(PREDICADOFINREGISTRO);
    add(predicadoFinRegistroSchema, ontologias.PredicadoFinRegistro.class);

    PredicateSchema predicadoInicioCallMarketSchema = new PredicateSchema(PREDICADOINICIOCALLMARKET);
    add(predicadoInicioCallMarketSchema, ontologias.PredicadoInicioCallMarket.class);
    PredicateSchema predicadoFinCallMarketSchema = new PredicateSchema(PREDICADOFINCALLMARKET);
    add(predicadoFinCallMarketSchema, ontologias.PredicadoFinCallMarket.class);


    // adding fields
    conceptoProductoSchema.add(CONCEPTOPRODUCTO_DESCRIPCION, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.OPTIONAL);
    conceptoProductoSchema.add(CONCEPTOPRODUCTO_NOMBRE, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.MANDATORY);
    conceptoProductoSchema.add(CONCEPTOPRODUCTO_IDPRODUCTO, (TermSchema)getSchema(BasicOntology.INTEGER), ObjectSchema.MANDATORY);
    conceptoNotificacionVentaSchema.add(CONCEPTONOTIFICACIONVENTA_PRECIO, (TermSchema)getSchema(BasicOntology.FLOAT), ObjectSchema.MANDATORY);
    conceptoNotificacionVentaSchema.add(CONCEPTONOTIFICACIONVENTA_FECHA, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.MANDATORY);
    conceptoNotificacionVentaSchema.add(CONCEPTONOTIFICACIONVENTA_IDNOTIFICACIONVENTA, (TermSchema)getSchema(BasicOntology.INTEGER), ObjectSchema.MANDATORY);
    conceptoNotificacionVentaSchema.add(CONCEPTONOTIFICACIONVENTA_IDPRODUCTO, (TermSchema)getSchema(BasicOntology.INTEGER), ObjectSchema.MANDATORY);
    conceptoNotificacionVentaSchema.add(CONCEPTONOTIFICACIONVENTA_IDVENDEDOR, (TermSchema)getSchema(BasicOntology.INTEGER), ObjectSchema.MANDATORY);
    conceptoNotificacionVentaSchema.add(CONCEPTONOTIFICACIONVENTA_CANTIDAD, (TermSchema)getSchema(BasicOntology.INTEGER), ObjectSchema.MANDATORY);
    conceptoBursatilSchema.add(CONCEPTOBURSATIL_SALDO, (TermSchema)getSchema(BasicOntology.FLOAT), ObjectSchema.MANDATORY);
    conceptoBursatilSchema.add(CONCEPTOBURSATIL_NOMBRE, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.MANDATORY);
    conceptoBursatilSchema.add(CONCEPTOBURSATIL_TIPO, (TermSchema)getSchema(BasicOntology.INTEGER), ObjectSchema.MANDATORY);
    conceptoBursatilSchema.add(CONCEPTOBURSATIL_IDBURSATIL, (TermSchema)getSchema(BasicOntology.INTEGER), ObjectSchema.MANDATORY);
    conceptoNotificacionCompraSchema.add(CONCEPTONOTIFICACIONCOMPRA_PRECIO, (TermSchema)getSchema(BasicOntology.FLOAT), ObjectSchema.MANDATORY);
    conceptoNotificacionCompraSchema.add(CONCEPTONOTIFICACIONCOMPRA_FECHA, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.MANDATORY);
    conceptoNotificacionCompraSchema.add(CONCEPTONOTIFICACIONCOMPRA_IDCOMPRADOR, (TermSchema)getSchema(BasicOntology.INTEGER), ObjectSchema.MANDATORY);
    conceptoNotificacionCompraSchema.add(CONCEPTONOTIFICACIONCOMPRA_IDNOTIFICACIONCOMPRA, (TermSchema)getSchema(BasicOntology.INTEGER), ObjectSchema.MANDATORY);
    conceptoNotificacionCompraSchema.add(CONCEPTONOTIFICACIONCOMPRA_IDPRODUCTO, (TermSchema)getSchema(BasicOntology.INTEGER), ObjectSchema.MANDATORY);
    conceptoNotificacionCompraSchema.add(CONCEPTONOTIFICACIONCOMPRA_CANTIDAD, (TermSchema)getSchema(BasicOntology.INTEGER), ObjectSchema.MANDATORY);
    conceptoOfertaCompraSchema.add(CONCEPTOOFERTACOMPRA_IDOFERTACOMPRA, (TermSchema)getSchema(BasicOntology.INTEGER), ObjectSchema.MANDATORY);
    conceptoOfertaCompraSchema.add(CONCEPTOOFERTACOMPRA_FECHA, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.MANDATORY);
    conceptoOfertaCompraSchema.add(CONCEPTOOFERTACOMPRA_IDCOMPRADOR, (TermSchema)getSchema(BasicOntology.INTEGER), ObjectSchema.MANDATORY);
    conceptoOfertaCompraSchema.add(CONCEPTOOFERTACOMPRA_PRECIOCOMPRA, (TermSchema)getSchema(BasicOntology.FLOAT), ObjectSchema.MANDATORY);
    conceptoOfertaCompraSchema.add(CONCEPTOOFERTACOMPRA_CANTIDAD, (TermSchema)getSchema(BasicOntology.INTEGER), ObjectSchema.MANDATORY);
    
    conceptoOfertaCompraSchema.add(CONCEPTOOFERTACOMPRA_PERIODO, (TermSchema)getSchema(BasicOntology.INTEGER), ObjectSchema.MANDATORY);
    conceptoCalceSchema.add(CONCEPTOCALCE_IDOFERTACOMPRA, (TermSchema)getSchema(BasicOntology.INTEGER), ObjectSchema.MANDATORY);
    conceptoCalceSchema.add(CONCEPTOCALCE_FECHA, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.MANDATORY);
    conceptoCalceSchema.add(CONCEPTOCALCE_IDCALCE, (TermSchema)getSchema(BasicOntology.INTEGER), ObjectSchema.MANDATORY);
    conceptoCalceSchema.add(CONCEPTOCALCE_IDPRODUCTO, (TermSchema)getSchema(BasicOntology.INTEGER), ObjectSchema.MANDATORY);
    conceptoCalceSchema.add(CONCEPTOCALCE_PRECIOSUGERIDO, (TermSchema)getSchema(BasicOntology.FLOAT), ObjectSchema.MANDATORY);
    conceptoCalceSchema.add(CONCEPTOCALCE_IDOFERTAVENTA, (TermSchema)getSchema(BasicOntology.INTEGER), ObjectSchema.MANDATORY);
    conceptoCalceSchema.add(CONCEPTOCALCE_CANTIDAD, (TermSchema)getSchema(BasicOntology.INTEGER), ObjectSchema.MANDATORY);
    conceptoRegistroSchema.add(CONCEPTOREGISTRO_FECHA, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.MANDATORY);
    conceptoRegistroSchema.add(CONCEPTOREGISTRO_IDBURSATIL, (TermSchema)getSchema(BasicOntology.INTEGER), ObjectSchema.MANDATORY);
    conceptoOfertaVentaSchema.add(CONCEPTOOFERTAVENTA_FECHA, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.MANDATORY);
    conceptoOfertaVentaSchema.add(CONCEPTOOFERTAVENTA_PRECIOVENTA, (TermSchema)getSchema(BasicOntology.FLOAT), ObjectSchema.MANDATORY);
    conceptoOfertaVentaSchema.add(CONCEPTOOFERTAVENTA_IDVENDEDOR, (TermSchema)getSchema(BasicOntology.INTEGER), ObjectSchema.MANDATORY);
    conceptoOfertaVentaSchema.add(CONCEPTOOFERTAVENTA_IDOFERTAVENTA, (TermSchema)getSchema(BasicOntology.INTEGER), ObjectSchema.MANDATORY);
    conceptoOfertaVentaSchema.add(CONCEPTOOFERTAVENTA_CANTIDAD, (TermSchema)getSchema(BasicOntology.INTEGER), ObjectSchema.MANDATORY);
    
    conceptoOfertaVentaSchema.add(CONCEPTOOFERTAVENTA_PERIODO, (TermSchema)getSchema(BasicOntology.INTEGER), ObjectSchema.MANDATORY);
    predicadoRegistrarAgenteBursatilSchema.add(PREDICADOREGISTRARAGENTEBURSATIL_BURSATIL, conceptoBursatilSchema, ObjectSchema.MANDATORY);
    predicadoCancelarCompraSchema.add(PREDICADOCANCELARCOMPRA_OFERTACOMPRA, conceptoOfertaCompraSchema, ObjectSchema.MANDATORY);
    predicadoFinSubastaSchema.add(PREDICADOFINSUBASTA_FINSUBASTA, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.MANDATORY);
    predicadoNotificarCompraSchema.add(PREDICADONOTIFICARCOMPRA_NOTIFICACIONCOMPRA, conceptoNotificacionCompraSchema, ObjectSchema.MANDATORY);
    predicadoConfirmarRegistroSchema.add(PREDICADOCONFIRMARREGISTRO_REGISTRO, conceptoRegistroSchema, ObjectSchema.MANDATORY);
    predicadoModificarVentaSchema.add(PREDICADOMODIFICARVENTA_OFERTAVENTA, conceptoOfertaVentaSchema, ObjectSchema.MANDATORY);
    predicadoModificarCompraSchema.add(PREDICADOMODIFICARCOMPRA_OFERTACOMPRA, conceptoOfertaCompraSchema, ObjectSchema.MANDATORY);
    predicadoNotificarVentaSchema.add(PREDICADONOTIFICARVENTA_NOTIFICACIONVENTA, conceptoNotificacionVentaSchema, ObjectSchema.MANDATORY);
    predicadoConfirmarOfertaSchema.add(PREDICADOCONFIRMAROFERTA_CONFIRMACIONOFERTA, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.MANDATORY);
    predicadoCancelarVentaSchema.add(PREDICADOCANCELARVENTA_OFERTAVENTA, conceptoOfertaVentaSchema, ObjectSchema.MANDATORY);
    predicadoRegistrarCompraSchema.add(PREDICADOREGISTRARCOMPRA_OFERTACOMPRA, conceptoOfertaCompraSchema, ObjectSchema.MANDATORY);
    predicadoRegistrarCompraSchema.add(PREDICADOREGISTRARCOMPRA_PRODUCTO, conceptoProductoSchema, ObjectSchema.OPTIONAL);
    predicadoEnEsperaSchema.add(PREDICADOENESPERA_ENESPERA, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.MANDATORY);
    predicadoRegistrarVentaSchema.add(PREDICADOREGISTRARVENTA_PRODUCTO, conceptoProductoSchema, ObjectSchema.OPTIONAL);
    predicadoRegistrarVentaSchema.add(PREDICADOREGISTRARVENTA_OFERTAVENTA, conceptoOfertaVentaSchema, ObjectSchema.MANDATORY);
    predicadoInicioSubastaSchema.add(PREDICADOINICIOSUBASTA_INICIOSUBASTA, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.MANDATORY);
    predicadoFinRegistroSchema.add(PREDICADOFINREGISTRO_FINREGISTRO, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.MANDATORY);

    predicadoInicioCallMarketSchema.add(PREDICADOINICIOCALLMARKET_PRODUCTO, conceptoProductoSchema, ObjectSchema.MANDATORY);
    predicadoFinCallMarketSchema.add(PREDICADOFINCALLMARKET_PRODUCTO, conceptoProductoSchema, ObjectSchema.MANDATORY);

    predicadoInicioCallMarketSchema.add(PREDICADOINICIOCALLMARKET_MOMENTO, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.MANDATORY);
    predicadoFinCallMarketSchema.add(PREDICADOFINCALLMARKET_MOMENTO, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.MANDATORY);

    predicadoCancelarVentaSchema.add(PREDICADOCANCELARVENTA_CONCEPTO, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.MANDATORY);
    predicadoCancelarVentaSchema.add(PREDICADOCANCELARVENTA_PRODUCTO, (TermSchema)getSchema(BasicOntology.INTEGER), ObjectSchema.MANDATORY);

    predicadoCancelarCompraSchema.add(PREDICADOCANCELARCOMPRA_CONCEPTO, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.MANDATORY);
    predicadoCancelarCompraSchema.add(PREDICADOCANCELARCOMPRA_PRODUCTO, (TermSchema)getSchema(BasicOntology.INTEGER), ObjectSchema.MANDATORY);


    // adding name mappings

    // adding inheritance

   }catch (java.lang.Exception e) {e.printStackTrace();}
  }
  }
