/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ErrorCampoVacio.java
 *
 * Created on 01/11/2009, 22:07:07
 */

package interfaz;

import java.awt.GridLayout;
import javax.swing.JLabel;

/**
 *
 * @author Sebas
 */
public class ErrorDatoNoValido extends javax.swing.JFrame {
    /** Creates new form ErrorCampoVacio */
    public ErrorDatoNoValido(String vacio, String invalido) {
        initComponents();
        this.setLocationRelativeTo(null);

        String[] vacios = vacio.split("[\n]");
        String[] invalidos = invalido.split("[\n]");
        int nCamposVacio = vacios.length;
        int nCamposErroneo = invalidos.length;
        labelVacio.setVisible(false);
        labelErroneo.setVisible(false);
        panelVacio.setVisible(false);
        panelErroneo.setVisible(false);

        panelVacio.setLayout(new GridLayout(nCamposVacio, 1));
        panelErroneo.setLayout(new GridLayout(nCamposErroneo, 1));

        if (nCamposVacio > 0) {
            labelVacio.setVisible(true);
            panelVacio.setVisible(true);
            for (int i = 0; i < nCamposVacio; ++i) {
                JLabel label = new JLabel(vacios[i]);
                panelVacio.add(label);
            }
        }
        if (nCamposErroneo > 0) {
            labelErroneo.setVisible(true);
            panelErroneo.setVisible(true);
            for (int i = 0; i < nCamposErroneo; ++i) {
                JLabel label = new JLabel(invalidos[i]);
                panelErroneo.add(label);
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonOK = new javax.swing.JButton();
        labelError = new javax.swing.JLabel();
        panelVacio = new javax.swing.JPanel();
        labelVacio = new javax.swing.JLabel();
        labelErroneo = new javax.swing.JLabel();
        panelErroneo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonOK.setText("OK");
        botonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOKActionPerformed(evt);
            }
        });

        labelError.setText("ERROR!!!");

        javax.swing.GroupLayout panelVacioLayout = new javax.swing.GroupLayout(panelVacio);
        panelVacio.setLayout(panelVacioLayout);
        panelVacioLayout.setHorizontalGroup(
            panelVacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 319, Short.MAX_VALUE)
        );
        panelVacioLayout.setVerticalGroup(
            panelVacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        labelVacio.setText("Los siguientes campos están vacíos:");

        labelErroneo.setText("Los siguientes datos son erróneos:");

        javax.swing.GroupLayout panelErroneoLayout = new javax.swing.GroupLayout(panelErroneo);
        panelErroneo.setLayout(panelErroneoLayout);
        panelErroneoLayout.setHorizontalGroup(
            panelErroneoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 319, Short.MAX_VALUE)
        );
        panelErroneoLayout.setVerticalGroup(
            panelErroneoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(146, Short.MAX_VALUE)
                .addComponent(labelError, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(152, Short.MAX_VALUE)
                .addComponent(botonOK)
                .addGap(150, 150, 150))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelErroneo, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelVacio, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panelVacio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panelErroneo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelVacio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelVacio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(labelErroneo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelErroneo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(botonOK)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOKActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_botonOKActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ErrorDatoNoValido("", "").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonOK;
    private javax.swing.JLabel labelErroneo;
    private javax.swing.JLabel labelError;
    private javax.swing.JLabel labelVacio;
    private javax.swing.JPanel panelErroneo;
    private javax.swing.JPanel panelVacio;
    // End of variables declaration//GEN-END:variables

}
