/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * parametros_simulacion.java
 *
 * Created on 18/12/2008, 04:33:03 PM
 */

package interfaz;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jdom.*;
import org.jdom.output.*;
/**
 *
 * @author Alejo
 */

 ////////////////////////////////////////////////////////////////////////////////////
    //////////////////////////////////INICIO CLASE PARAMETROS DE LA SIMULACION /////////
    ///////////////////////////////////////////////////////////////////////////////////
public class parametros_simulacion extends javax.swing.JFrame {


    /** Creates new form parametros_simulacion */
    public parametros_simulacion() {
        initComponents();
        this.setLocationRelativeTo(null);


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        ParametrosPeriodos = new javax.swing.JLabel();
        ParametrosAgentes = new javax.swing.JLabel();
        ParametrosAcciones = new javax.swing.JLabel();
        ParametrosContinuar = new javax.swing.JButton();
        ParametrosCantidadPeriodos = new javax.swing.JSpinner();
        ParametrosCantidadAgentes = new javax.swing.JSpinner();
        ParametrosCantidadAcciones = new javax.swing.JSpinner();
        ParametrosRepeticiones = new javax.swing.JLabel();
        ParametrosCantidadRepeticiones = new javax.swing.JSpinner();

        setTitle("General aspect of simulation");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        ParametrosPeriodos.setText("Number of periods (days)");

        ParametrosAgentes.setText("Number of agents");

        ParametrosAcciones.setText("Number of stocks");

        ParametrosContinuar.setText("Continue");
        ParametrosContinuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ParametrosContinuarMouseClicked(evt);
            }
        });

        ParametrosCantidadPeriodos.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        ParametrosCantidadAgentes.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        ParametrosCantidadAcciones.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        ParametrosRepeticiones.setText("Iterations");

        ParametrosCantidadRepeticiones.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ParametrosAcciones)
                            .addComponent(ParametrosAgentes)
                            .addComponent(ParametrosPeriodos)
                            .addComponent(ParametrosRepeticiones))
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ParametrosCantidadPeriodos, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ParametrosCantidadAgentes, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ParametrosCantidadAcciones, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ParametrosCantidadRepeticiones, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(ParametrosContinuar)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ParametrosCantidadPeriodos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ParametrosPeriodos))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ParametrosCantidadAgentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ParametrosAgentes))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ParametrosCantidadAcciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ParametrosAcciones))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ParametrosRepeticiones)
                    .addComponent(ParametrosCantidadRepeticiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ParametrosContinuar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ParametrosContinuarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ParametrosContinuarMouseClicked

        String strCantidadAgentes = ParametrosCantidadAgentes.getValue().toString();
        String strCantidadPeriodos = ParametrosCantidadPeriodos.getValue().toString();
        String strCantidadAcciones = ParametrosCantidadAcciones.getValue().toString();
        String strCantidadRepeticiones = ParametrosCantidadRepeticiones.getValue().toString();

        try {


            Main.agentesGenerar=Integer.parseInt(strCantidadAgentes);
            Main.periodosSimulacion=Integer.parseInt(strCantidadPeriodos);
            Main.totalAcciones = Integer.parseInt(strCantidadAcciones);
            Main.numeroRepeticiones = Integer.parseInt(strCantidadRepeticiones);
            
            //ConexionBD BD = new ConexionBD("mysql");
            Main.numeroBursatiles = Main.agentesGenerar;
            //BD.inicializarBD();
            //BD.cerrarConexion();

            //-----------------------CREACIÓN DEL ARCHIVO XML --------------------------------
            File fichero = new File(Main.nombreArchivo);
            if(fichero.exists())
            {
                fichero.delete();
            }
            fichero.createNewFile();

            Element raiz = new Element("Subasta");
            raiz.setAttribute("periodos", Integer.toString(Main.periodosSimulacion));
            raiz.setAttribute("numeroAgentes", Integer.toString(Main.numeroBursatiles));
            raiz.setAttribute("numeroAcciones", Integer.toString(Main.totalAcciones));
            raiz.setAttribute("numeroRepeticiones", Integer.toString(Main.numeroRepeticiones));

            //raiz.setAttribute("cargarSeries", "0");

            Element acciones = new Element("acciones");
            Element cotizaciones = new Element("cotizaciones");
            Element agentes = new Element("agentes");
            raiz.addContent(acciones);
            raiz.addContent(cotizaciones);
            raiz.addContent(agentes);
            Document doc = new Document(raiz);
            XMLOutputter out=new XMLOutputter(Format.getPrettyFormat());
            FileOutputStream file=new FileOutputStream(Main.nombreArchivo);
            out.output(doc,file);
            file.flush();
            file.close();

            Main.nombreArchivo=fichero.getCanonicalPath();
            System.out.println(Main.nombreArchivo);

        //----------------------FIN CREACIÓN DEL ARCHIVO XML -----------------------------



            
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    Acciones acciones1 = new Acciones(Main.totalAcciones, Main.agentesGenerar);
                }
            });
            

            //this.setVisible(false);
            this.dispose();
        }
 catch (IOException ex) {
            Logger.getLogger(parametros_simulacion.class.getName()).log(Level.SEVERE, null, ex);
        }        catch(Exception e)
        {
            e.printStackTrace();
        }

    }//GEN-LAST:event_ParametrosContinuarMouseClicked

    /**
    * @param args the command line arguments
    */
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new parametros_simulacion().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ParametrosAcciones;
    private javax.swing.JLabel ParametrosAgentes;
    private javax.swing.JSpinner ParametrosCantidadAcciones;
    private javax.swing.JSpinner ParametrosCantidadAgentes;
    private javax.swing.JSpinner ParametrosCantidadPeriodos;
    private javax.swing.JSpinner ParametrosCantidadRepeticiones;
    private javax.swing.JButton ParametrosContinuar;
    private javax.swing.JLabel ParametrosPeriodos;
    private javax.swing.JLabel ParametrosRepeticiones;
    private javax.swing.ButtonGroup buttonGroup1;
    // End of variables declaration//GEN-END:variables


  
////////////////////////////////////////////////////////////////////////////////////
    //////////////////////////////////FIN CLASE PARAMETROS DE LOS AGENTES /////////
    ///////////////////////////////////////////////////////////////////////////////////


}
