/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * pop.java
 *
 * Created on 30/01/2009, 05:05:57 PM
 */

package interfaz;

/**
 *
 * @author Alejo
 */
public class pop extends javax.swing.JFrame {

    /** Creates new form pop */
    public pop(String nombre, int dias) {
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle(nombre);
        PopEtiqueta.setText("Have been saved "+dias+" dates from the history");
        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PopEtiqueta = new javax.swing.JLabel();
        PopContinuar = new javax.swing.JButton();

        setBounds(new java.awt.Rectangle(100, 200, 0, 0));
        setResizable(false);

        PopEtiqueta.setText("Se ha guardado correctamente el historial");

        PopContinuar.setText("Continuar");
        PopContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PopContinuarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(PopEtiqueta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PopContinuar))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(PopEtiqueta)
                .addGap(18, 18, 18)
                .addComponent(PopContinuar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PopContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PopContinuarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_PopContinuarActionPerformed

    /**
    * @param args the command line arguments
    */
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pop("pepe",12).setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PopContinuar;
    private javax.swing.JLabel PopEtiqueta;
    // End of variables declaration//GEN-END:variables

}
