/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Simulacion.java
 *
 * Created on 5/02/2009, 01:55:14 PM
 */

package interfaz;

import java.io.File;

/**
 *
 * @author Alejo
 */
public class Simulacion extends javax.swing.JFrame {

    /** Creates new form Simulacion */
    public Simulacion() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SimulacionFinal = new javax.swing.JLabel();
        SimulacionContinuar = new javax.swing.JButton();

        setBounds(new java.awt.Rectangle(300, 300, 0, 0));
        setResizable(false);

        SimulacionFinal.setText("The simulation is over");

        SimulacionContinuar.setText("Continue");
        SimulacionContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimulacionContinuarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addComponent(SimulacionFinal)
                .addGap(67, 67, 67))
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(SimulacionContinuar)
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(SimulacionFinal)
                .addGap(18, 18, 18)
                .addComponent(SimulacionContinuar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SimulacionContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimulacionContinuarActionPerformed
       this.setVisible(false);
       Main.MenuResultados.setEnabled(true);
       //Principal.panelGrafico.setVisible(false);
       
       File file = new File("CalceRunTime.txt");
       file.delete();



    }//GEN-LAST:event_SimulacionContinuarActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Simulacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SimulacionContinuar;
    private javax.swing.JLabel SimulacionFinal;
    // End of variables declaration//GEN-END:variables

}
